language: node_js
sudo: false
dist: trusty
env:
  - PGUSER=postgres PGDATABASE=postgres

node_js: "6"
addons:
  postgresql: "9.6"

matrix:
  include:
    - node_js: "0.10"
      addons:
        postgresql: "9.3"
    - node_js: "0.10"
      addons:
        postgresql: "9.5"
    - node_js: "4"
      addons:
        postgresql: "9.5"
    - node_js: "6"
      addons:
        postgresql: "9.3"
    - node_js: "6"
      addons:
        postgresql: "9.4"
    - node_js: "6"
      addons:
        postgresql: "9.5"
