before_install:
  - sudo mv /etc/apt/sources.list.d/pgdg-source.list* /tmp
  - sudo apt-get -qq purge postgis* postgresql*
  - sudo rm -Rf /var/lib/postgresql /etc/postgresql
  - sudo apt-add-repository --yes ppa:cartodb/postgresql-9.3
  - sudo apt-add-repository --yes ppa:cartodb/gis
  - sudo apt-get update -q
  - sudo apt-get install -q gdal-bin postgresql-9.3-postgis-2.1
  - createdb template_postgis
  - psql -c "CREATE EXTENSION postgis" template_postgis
  - ./configure

language: node_js
node_js:
  - "0.8"
  - "0.10"
